import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode;

}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
    <html lang="en" >
      <body>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
    </ClerkProvider>
  );
}
